"""Deterministic research engine for the price-cycle-equities skill."""

from .models import (
    Bar,
    DataSet,
    EvidenceItem,
    FeatureRow,
    Market,
    ObservedEvent,
    PhaseAssessment,
    PriceBasis,
    Provenance,
    TriState,
)
from .parameters import ResearchParameters
from .market_rules import RuleResolution, RuleResolutionStatus, rules_at
from .providers import (
    CONFIG_SCHEMA_VERSION,
    CsvFileProvider,
    CredentialSpec,
    CredentialUnavailableError,
    DEFAULT_PROVIDER_CATALOG,
    DataAssuranceMode,
    DataRequest,
    EnvironmentCredentialResolver,
    ProviderAccessMode,
    ProviderAttempt,
    ProviderAttemptStatus,
    ProviderFailure,
    ProviderCatalog,
    ProviderConfigError,
    ProviderConfiguration,
    ProviderDescriptor,
    ProviderLoadResult,
    ProviderRegistry,
    ProviderResolutionError,
    ProviderRoute,
    ProviderRouter,
    ProviderSettings,
    SecretValue,
    SourceArtifact,
    TUSHARE_TOKEN_SPEC,
    BlockedTushareTransport,
    TushareDailyProvider,
    TushareTransport,
    TushareTransportError,
    load_provider_config,
)

__all__ = [
    "Bar",
    "CONFIG_SCHEMA_VERSION",
    "CsvFileProvider",
    "CredentialSpec",
    "CredentialUnavailableError",
    "DEFAULT_PROVIDER_CATALOG",
    "DataAssuranceMode",
    "DataSet",
    "DataRequest",
    "EnvironmentCredentialResolver",
    "EvidenceItem",
    "FeatureRow",
    "Market",
    "ObservedEvent",
    "PhaseAssessment",
    "PriceBasis",
    "ProviderAccessMode",
    "ProviderAttempt",
    "ProviderAttemptStatus",
    "ProviderFailure",
    "ProviderCatalog",
    "ProviderConfigError",
    "ProviderConfiguration",
    "ProviderDescriptor",
    "ProviderLoadResult",
    "ProviderRegistry",
    "ProviderResolutionError",
    "ProviderRoute",
    "ProviderRouter",
    "ProviderSettings",
    "Provenance",
    "ResearchParameters",
    "RuleResolution",
    "RuleResolutionStatus",
    "SourceArtifact",
    "SecretValue",
    "TUSHARE_TOKEN_SPEC",
    "BlockedTushareTransport",
    "TushareDailyProvider",
    "TushareTransport",
    "TushareTransportError",
    "TriState",
    "rules_at",
    "load_provider_config",
]

__version__ = "0.2.0-alpha.2-dev.2"
