"""Provider-neutral data loading and deterministic fallback routing."""

from .base import (
    DataAssuranceMode,
    DataProvider,
    DataRequest,
    ProviderAttempt,
    ProviderAttemptStatus,
    ProviderFailure,
    ProviderLoadResult,
    ProviderRegistry,
    ProviderResolutionError,
    ProviderRouter,
    SourceArtifact,
)
from .csv_file import CsvFileProvider
from .config import (
    CONFIG_SCHEMA_VERSION,
    CredentialSpec,
    CredentialUnavailableError,
    DEFAULT_PROVIDER_CATALOG,
    EODHD_TOKEN_SPEC,
    EnvironmentCredentialResolver,
    ProviderAccessMode,
    ProviderCatalog,
    ProviderConfigError,
    ProviderConfiguration,
    ProviderDescriptor,
    ProviderRoute,
    ProviderSettings,
    SecretValue,
    TUSHARE_TOKEN_SPEC,
    load_provider_config,
)
from .eodhd import (
    EodhdDailyProvider,
    EodhdTransport,
    EodhdTransportError,
    HISTORY_CALENDAR_DAYS as EODHD_HISTORY_CALENDAR_DAYS,
    HttpsEodhdTransport,
)
from .runtime import (
    ProviderRuntimeError,
    build_remote_registry,
    resolve_remote_route,
)
from .tushare import (
    BlockedTushareTransport,
    HISTORY_CALENDAR_DAYS,
    TushareDailyProvider,
    TushareTransport,
    TushareTransportError,
)

__all__ = [
    "BlockedTushareTransport",
    "CONFIG_SCHEMA_VERSION",
    "CredentialSpec",
    "CredentialUnavailableError",
    "CsvFileProvider",
    "DEFAULT_PROVIDER_CATALOG",
    "DataAssuranceMode",
    "DataProvider",
    "DataRequest",
    "EODHD_HISTORY_CALENDAR_DAYS",
    "EODHD_TOKEN_SPEC",
    "EnvironmentCredentialResolver",
    "EodhdDailyProvider",
    "EodhdTransport",
    "EodhdTransportError",
    "HISTORY_CALENDAR_DAYS",
    "HttpsEodhdTransport",
    "ProviderAccessMode",
    "ProviderAttempt",
    "ProviderAttemptStatus",
    "ProviderCatalog",
    "ProviderConfigError",
    "ProviderConfiguration",
    "ProviderDescriptor",
    "ProviderFailure",
    "ProviderLoadResult",
    "ProviderRegistry",
    "ProviderResolutionError",
    "ProviderRoute",
    "ProviderRouter",
    "ProviderRuntimeError",
    "ProviderSettings",
    "SecretValue",
    "SourceArtifact",
    "TUSHARE_TOKEN_SPEC",
    "TushareDailyProvider",
    "TushareTransport",
    "TushareTransportError",
    "build_remote_registry",
    "load_provider_config",
    "resolve_remote_route",
]
